export enum AuditAction {
  // Authentication
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',

  // Members
  CREATE_MEMBER = 'CREATE_MEMBER',
  UPDATE_MEMBER = 'UPDATE_MEMBER',
  DELETE_MEMBER = 'DELETE_MEMBER',

  // Users
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Departments
  CREATE_DEPARTMENT = 'CREATE_DEPARTMENT',
  UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT',
  DELETE_DEPARTMENT = 'DELETE_DEPARTMENT',
  ADD_DEPARTMENT_MEMBER = 'ADD_DEPARTMENT_MEMBER',
  UPDATE_DEPARTMENT_MEMBER = 'UPDATE_DEPARTMENT_MEMBER',
  REMOVE_DEPARTMENT_MEMBER = 'REMOVE_DEPARTMENT_MEMBER',

  // Events
  CREATE_EVENT = 'CREATE_EVENT',
  UPDATE_EVENT = 'UPDATE_EVENT',
  DELETE_EVENT = 'DELETE_EVENT',

  // Communications
  SEND_COMMUNICATION = 'SEND_COMMUNICATION',
  SCHEDULE_COMMUNICATION = 'SCHEDULE_COMMUNICATION',

  // Prayer Requests
  CREATE_PRAYER_REQUEST = 'CREATE_PRAYER_REQUEST',
  ASSIGN_PRAYER_REQUEST = 'ASSIGN_PRAYER_REQUEST',
  ANSWER_PRAYER_REQUEST = 'ANSWER_PRAYER_REQUEST',
  CLOSE_PRAYER_REQUEST = 'CLOSE_PRAYER_REQUEST',

  // Giving
  CREATE_GIVING = 'CREATE_GIVING',
  UPDATE_GIVING = 'UPDATE_GIVING',
  DELETE_GIVING = 'DELETE_GIVING',

  // Generic
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  // Notifications
  CREATE_NOTIFICATION = 'CREATE_NOTIFICATION',
  READ_NOTIFICATION = 'READ_NOTIFICATION',
  READ_ALL_NOTIFICATIONS = 'READ_ALL_NOTIFICATIONS',
  DELETE_NOTIFICATION = 'DELETE_NOTIFICATION',
  DELETE_OLD_NOTIFICATIONS = 'DELETE_OLD_NOTIFICATIONS',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
}