export enum AuditAction {
  // Authentication & Credentials
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',

  // System Users
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Members
  CREATE_MEMBER = 'CREATE_MEMBER',
  UPDATE_MEMBER = 'UPDATE_MEMBER',
  DELETE_MEMBER = 'DELETE_MEMBER',

  // Workers
  CREATE_WORKER = 'CREATE_WORKER',
  UPDATE_WORKER = 'UPDATE_WORKER',
  DELETE_WORKER = 'DELETE_WORKER',
  RECORD_WORKER_ATTENDANCE = 'RECORD_WORKER_ATTENDANCE',

  // Worker Training & Pipeline
  CREATE_WORKER_PIPELINE = 'CREATE_WORKER_PIPELINE',
  UPDATE_WORKER_PIPELINE_STAGE = 'UPDATE_WORKER_PIPELINE_STAGE',
  PROMOTE_TO_WORKER = 'PROMOTE_TO_WORKER',
  ASSIGN_WORKER_MENTOR = 'ASSIGN_WORKER_MENTOR',

  // Departments
  CREATE_DEPARTMENT = 'CREATE_DEPARTMENT',
  UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT',
  DELETE_DEPARTMENT = 'DELETE_DEPARTMENT',
  ADD_DEPARTMENT_MEMBER = 'ADD_DEPARTMENT_MEMBER',
  UPDATE_DEPARTMENT_MEMBER = 'UPDATE_DEPARTMENT_MEMBER',
  REMOVE_DEPARTMENT_MEMBER = 'REMOVE_DEPARTMENT_MEMBER',

  // Ministries
  CREATE_MINISTRY = 'CREATE_MINISTRY',
  UPDATE_MINISTRY = 'UPDATE_MINISTRY',
  DELETE_MINISTRY = 'DELETE_MINISTRY',
  ADD_MINISTRY_MEMBER = 'ADD_MINISTRY_MEMBER',
  UPDATE_MINISTRY_MEMBER = 'UPDATE_MINISTRY_MEMBER',
  REMOVE_MINISTRY_MEMBER = 'REMOVE_MINISTRY_MEMBER',

  // Leadership Classes & Training
  CREATE_LEADERSHIP_CLASS = 'CREATE_LEADERSHIP_CLASS',
  UPDATE_LEADERSHIP_CLASS = 'UPDATE_LEADERSHIP_CLASS',
  DELETE_LEADERSHIP_CLASS = 'DELETE_LEADERSHIP_CLASS',
  ENROLL_LEADERSHIP_CLASS = 'ENROLL_LEADERSHIP_CLASS',
  UPDATE_LEADERSHIP_ENROLLMENT = 'UPDATE_LEADERSHIP_ENROLLMENT',
  UPDATE_LEADERSHIP_PROGRESS = 'UPDATE_LEADERSHIP_PROGRESS',
  CREATE_LEADERSHIP_SESSION = 'CREATE_LEADERSHIP_SESSION',

  // Events & Attendance
  CREATE_EVENT = 'CREATE_EVENT',
  UPDATE_EVENT = 'UPDATE_EVENT',
  DELETE_EVENT = 'DELETE_EVENT',
  PUBLISH_EVENT = 'PUBLISH_EVENT',
  CANCEL_EVENT = 'CANCEL_EVENT',
  RECORD_EVENT_ATTENDANCE = 'RECORD_EVENT_ATTENDANCE',
  VIEW_EVENT_ATTENDANCE = 'VIEW_EVENT_ATTENDANCE',

  // Communications & Messaging
  CREATE_COMMUNICATION = 'CREATE_COMMUNICATION',
  UPDATE_COMMUNICATION = 'UPDATE_COMMUNICATION',
  DELETE_COMMUNICATION = 'DELETE_COMMUNICATION',
  RESTORE_COMMUNICATION = 'RESTORE_COMMUNICATION',
  ARCHIVE_COMMUNICATION = 'ARCHIVE_COMMUNICATION',
  DUPLICATE_COMMUNICATION = 'DUPLICATE_COMMUNICATION',
  SEND_COMMUNICATION = 'SEND_COMMUNICATION',
  SEND_NEWSLETTER = 'SEND_NEWSLETTER',
  SCHEDULE_COMMUNICATION = 'SCHEDULE_COMMUNICATION',
  CANCEL_COMMUNICATION = 'CANCEL_COMMUNICATION',

  // Prayer Requests
  CREATE_PRAYER_REQUEST = 'CREATE_PRAYER_REQUEST',
  UPDATE_PRAYER_REQUEST = 'UPDATE_PRAYER_REQUEST',
  ASSIGN_PRAYER_REQUEST = 'ASSIGN_PRAYER_REQUEST',
  ANSWER_PRAYER_REQUEST = 'ANSWER_PRAYER_REQUEST',
  ADD_PRAYER_NOTE = 'ADD_PRAYER_NOTE',
  ARCHIVE_PRAYER_REQUEST = 'ARCHIVE_PRAYER_REQUEST',
  CLOSE_PRAYER_REQUEST = 'CLOSE_PRAYER_REQUEST',

  // Giving & Finance
  CREATE_GIVING = 'CREATE_GIVING',
  RECORD_GIVING = 'RECORD_GIVING',
  UPDATE_GIVING = 'UPDATE_GIVING',
  DELETE_GIVING = 'DELETE_GIVING',
  REFUND_GIVING = 'REFUND_GIVING',
  VIEW_GIVING_REPORT = 'VIEW_GIVING_REPORT',
  EXPORT_GIVING_REPORT = 'EXPORT_GIVING_REPORT',

  // Content (Blog, Sermons, Media)
  CREATE_BLOG_POST = 'CREATE_BLOG_POST',
  UPDATE_BLOG_POST = 'UPDATE_BLOG_POST',
  DELETE_BLOG_POST = 'DELETE_BLOG_POST',
  PUBLISH_BLOG_POST = 'PUBLISH_BLOG_POST',

  CREATE_SERMON = 'CREATE_SERMON',
  UPDATE_SERMON = 'UPDATE_SERMON',
  DELETE_SERMON = 'DELETE_SERMON',

  UPLOAD_MEDIA = 'UPLOAD_MEDIA',
  DELETE_MEDIA = 'DELETE_MEDIA',
  CREATE_MEDIA_GALLERY = 'CREATE_MEDIA_GALLERY',
  UPDATE_MEDIA_GALLERY = 'UPDATE_MEDIA_GALLERY',
  DELETE_MEDIA_GALLERY = 'DELETE_MEDIA_GALLERY',

  // Contact Messages & Subscriptions
  RESOLVE_CONTACT_MESSAGE = 'RESOLVE_CONTACT_MESSAGE',
  ASSIGN_CONTACT_MESSAGE = 'ASSIGN_CONTACT_MESSAGE',
  SUBSCRIBE = 'SUBSCRIBE',
  UNSUBSCRIBE = 'UNSUBSCRIBE',

  // System Invitations
  CREATE_INVITATION = 'CREATE_INVITATION',
  ACCEPT_INVITATION = 'ACCEPT_INVITATION',
  CANCEL_INVITATION = 'CANCEL_INVITATION',

  // Notifications
  CREATE_NOTIFICATION = 'CREATE_NOTIFICATION',
  READ_NOTIFICATION = 'READ_NOTIFICATION',
  READ_ALL_NOTIFICATIONS = 'READ_ALL_NOTIFICATIONS',
  DELETE_NOTIFICATION = 'DELETE_NOTIFICATION',
  DELETE_OLD_NOTIFICATIONS = 'DELETE_OLD_NOTIFICATIONS',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
  
  // Generic Fallbacks
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  
}